package org.chartsy.main;

import java.util.Collections;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.text.AbstractDocument;
import org.chartsy.main.data.DataProvider;
import org.chartsy.main.data.Exchange;
import org.chartsy.main.data.Stock;
import org.chartsy.main.managers.DataProviderManager;
import org.chartsy.main.managers.TemplateManager;
import org.chartsy.main.templates.Template;
import org.chartsy.main.utils.UppercaseDocumentFilter;
import org.chartsy.main.utils.autocomplete.StockAutoCompleter;
import org.openide.windows.WindowManager;

public class NewChartDialog extends javax.swing.JDialog
{

    private static final String defaultDataProvider = "MrSwing";
    private StockAutoCompleter completer = null;
    private Stock stock = null;
    private DataProvider dataProvider = null;
    private Template template = null;

    /** Creates new form NewChartDialog */
    public NewChartDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        setTitle("New Chart");
        initComponents();
        parent.setIconImage(WindowManager.getDefault().getMainWindow().getIconImage());
        getRootPane().setDefaultButton(btnNewChart);
        initForm();
    }

    private void initForm()
    {
        dataProvider = DataProviderManager.getDefault().getDataProvider(defaultDataProvider);
        List<String> dataProviders = DataProviderManager.getDefault().getDataProviders();
        Collections.sort(dataProviders);

        lstDataProvider.setMaximumRowCount(dataProviders.size());
        for (String s : dataProviders)
        {
            lstDataProvider.addItem(s);
        }
        lstDataProvider.setSelectedItem(defaultDataProvider);

        Object[] templates = TemplateManager.getDefault().getTemplateNames();
        for (Object temp : templates)
        {
            lstTemplate.addItem(temp);
        }
        lstTemplate.setSelectedItem(TemplateManager.getDefault().getDefaultTemplate());

        ((AbstractDocument) txtSymbol.getDocument()).setDocumentFilter(new UppercaseDocumentFilter());
        completer = new StockAutoCompleter(txtSymbol);
        completer.setDataProvider(dataProvider);
    }

    public Stock getStock()
    {
        return stock;
    }

    public DataProvider getDataProvider()
    {
        return dataProvider;
    }

    public Template getTemplate()
    {
        return template;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblSymbol = new javax.swing.JLabel();
        txtSymbol = new javax.swing.JTextField();
        lblDataProvider = new javax.swing.JLabel();
        lstDataProvider = new javax.swing.JComboBox();
        lblExchange = new javax.swing.JLabel();
        lstExchange = new javax.swing.JComboBox();
        lblTemplate = new javax.swing.JLabel();
        lstTemplate = new javax.swing.JComboBox();
        btnNewChart = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(NewChartDialog.class, "NewChartDialog.title")); // NOI18N

        lblLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/chartsy/main/resources/logo.png"))); // NOI18N
        lblLogo.setText(org.openide.util.NbBundle.getMessage(NewChartDialog.class, "NewChartDialog.lblLogo.text")); // NOI18N
        lblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSymbol.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblSymbol.setText(org.openide.util.NbBundle.getMessage(NewChartDialog.class, "NewChartDialog.lblSymbol.text")); // NOI18N

        txtSymbol.setColumns(6);
        txtSymbol.setText(org.openide.util.NbBundle.getMessage(NewChartDialog.class, "NewChartDialog.txtSymbol.text")); // NOI18N
        txtSymbol.setToolTipText(org.openide.util.NbBundle.getMessage(NewChartDialog.class, "NewChartDialog.txtSymbol.toolTipText")); // NOI18N

        lblDataProvider.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblDataProvider.setText(org.openide.util.NbBundle.getMessage(NewChartDialog.class, "NewChartDialog.lblDataProvider.text")); // NOI18N

        lstDataProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstDataProviderActionPerformed(evt);
            }
        });

        lblExchange.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblExchange.setText(org.openide.util.NbBundle.getMessage(NewChartDialog.class, "NewChartDialog.lblExchange.text")); // NOI18N

        lstExchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstExchangeActionPerformed(evt);
            }
        });

        lblTemplate.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblTemplate.setText(org.openide.util.NbBundle.getMessage(NewChartDialog.class, "NewChartDialog.lblTemplate.text")); // NOI18N

        btnNewChart.setText(org.openide.util.NbBundle.getMessage(NewChartDialog.class, "NewChartDialog.btnNewChart.text")); // NOI18N
        btnNewChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewChartActionPerformed(evt);
            }
        });

        btnCancel.setText(org.openide.util.NbBundle.getMessage(NewChartDialog.class, "NewChartDialog.btnCancel.text")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblSymbol)
                            .addGap(56, 56, 56)
                            .addComponent(txtSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTemplate)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDataProvider)
                                        .addComponent(lblExchange))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lstExchange, 0, 378, Short.MAX_VALUE)
                                        .addComponent(lstTemplate, 0, 378, Short.MAX_VALUE)
                                        .addComponent(lstDataProvider, 0, 378, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnNewChart)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnCancel)))))
                            .addGap(26, 26, 26)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSymbol)
                        .addComponent(txtSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDataProvider)
                        .addComponent(lstDataProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblExchange)
                        .addComponent(lstExchange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTemplate)
                        .addComponent(lstTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancel)
                        .addComponent(btnNewChart))
                    .addGap(11, 11, 11)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstDataProviderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lstDataProviderActionPerformed
    {//GEN-HEADEREND:event_lstDataProviderActionPerformed
        JComboBox list = (JComboBox) evt.getSource();
        String provider = (String) list.getSelectedItem();
        lstExchange.removeAllItems();
        dataProvider = DataProviderManager.getDefault().getDataProvider(provider);
        if (completer != null)
        {
            completer.setDataProvider(dataProvider);
        }
        Exchange[] exchanges = dataProvider.getExchanges();
        if (exchanges == null || exchanges.length == 0)
        {
            lblExchange.setVisible(false);
            lstExchange.setVisible(false);
        } else
        {
            for (Exchange exchange : exchanges)
            {
                lstExchange.addItem(exchange.getExchange());
            }
        }
}//GEN-LAST:event_lstDataProviderActionPerformed

    private void lstExchangeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lstExchangeActionPerformed
    {//GEN-HEADEREND:event_lstExchangeActionPerformed
        Object obj = lstDataProvider.getSelectedItem();
        if (obj != null)
        {
            DataProvider dp = DataProviderManager.getDefault().getDataProvider((String) obj);
            int i = lstExchange.getSelectedIndex();
            if (i != -1)
            {
                Exchange exchange = dp.getExchanges()[i];
                String symbol = txtSymbol.getText();

                if (symbol != null)
                {
                    symbol.trim();
                    String delimiter = ".";

                    if (symbol.contains(delimiter))
                    {
                        int index = symbol.indexOf(delimiter);
                        symbol = symbol.substring(0, index);
                    }

                    txtSymbol.setText(symbol + exchange.getSufix());
                }
            }
        }
}//GEN-LAST:event_lstExchangeActionPerformed

    private void btnNewChartActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNewChartActionPerformed
    {//GEN-HEADEREND:event_btnNewChartActionPerformed
        completer.stopTimer();
        dataProvider = DataProviderManager.getDefault().getDataProvider((String) lstDataProvider.getSelectedItem());
        Exchange exchange = dataProvider.getExchanges()[lstExchange.getSelectedIndex()];
        stock = new Stock(txtSymbol.getText(), exchange.getSufix());
        template = TemplateManager.getDefault().getTemplate(lstTemplate.getSelectedItem());
        setVisible(false);
}//GEN-LAST:event_btnNewChartActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        stock = null;
        dataProvider = null;
        template = null;
        setVisible(false);
}//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                NewChartDialog dialog = new NewChartDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {

                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNewChart;
    private javax.swing.JLabel lblDataProvider;
    private javax.swing.JLabel lblExchange;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSymbol;
    private javax.swing.JLabel lblTemplate;
    private javax.swing.JComboBox lstDataProvider;
    private javax.swing.JComboBox lstExchange;
    private javax.swing.JComboBox lstTemplate;
    private javax.swing.JTextField txtSymbol;
    // End of variables declaration//GEN-END:variables
}
